### ISSUE TITLE
Feature request: add `clear` function to metrics

### ISSUE THREAD

**Issue by balena** [deadtrickster/prometheus.erl#109]
Along metrics lifetime, sometimes it is needed to clear (erase, interrupt) existing metrics. This purposely generates "interrupted" metrics in analytics tools such as Grafana.

Example: a cluster where metrics need to be collected from a leader, and the "leader" label moves around the cluster nodes. During leader reelection, followers need to clear (erase, interrupt) their metrics.

**Comment by balena** [comment]
I've created such function and added unit tests: https://github.com/deadtrickster/prometheus.erl/pull/108

**Comment by RoadRunnr** [comment]
how is that different from the existing remove function?

**Comment by balena** [comment]
It is not much different. You can close this ticket.
