### ISSUE TITLE
Error compiling on rebar2 beacause of rebar3_archive_plugin 

### ISSUE THREAD

**Issue by NikolaBorisov** [deadtrickster/prometheus.erl#111]
Hello,

When I try to add prometheus.erl as dependency of a rebar2 project I get this error below:

It looks like it is caused by the rebar3_archive_plugin. Commenting out the last line in the rebar.config file fixes it.
Please advice

    Uncaught error in rebar_core: {'EXIT',
                               {function_clause,
                                [{code,which,
                                  [{rebar3_archive_plugin,"0.0.1"}],
                                  [{file,"code.erl"},{line,738}]},
                                 {rebar_core,'-plugin_modules/3-lc$^0/1-0-',
                                  1,
                                  [{file,"src/rebar_core.erl"},{line,573}]},
                                 {rebar_core,plugin_modules,3,
                                  [{file,"src/rebar_core.erl"},{line,573}]},
                                 {rebar_core,process_dir1,7,
                                  [{file,"src/rebar_core.erl"},{line,244}]},
                                 {rebar_core,process_each,5,
                                  [{file,"src/rebar_core.erl"},{line,351}]},
                                 {rebar_core,process_dir1,7,
                                  [{file,"src/rebar_core.erl"},{line,253}]},
                                 {rebar_core,process_commands,2,
                                  [{file,"src/rebar_core.erl"},{line,93}]},
                                 {rebar,main,1,
                                  [{file,"src/rebar.erl"},{line,58}]}]}}

**Comment by essen** [comment]
Maybe conditionally include it in the config here https://github.com/deadtrickster/prometheus.erl/blob/master/rebar.config.script rather than commenting it out.
