### ISSUE TITLE
Fix type spec hacks

### ISSUE THREAD

**Issue by yurrriq** [deadtrickster/prometheus.erl#12]
Related #5, #8.

- [x] [`prometheus_metric:value()`](https://github.com/deadtrickster/prometheus.erl/blob/60bc05871388d9fbed9c76b88e4178d7f0812cb1/src/prometheus_metric.erl#L39-L41)
- [x] Introduce separate types for [`prometheus_collector:callback()`](https://github.com/deadtrickster/prometheus.erl/blob/60bc05871388d9fbed9c76b88e4178d7f0812cb1/src/prometheus_collector.erl#L15-L18)
  - [x] `mf_callback()`
  - [x] `registry_callback()`
- [x] [`prometheus_collector:collect_mf/2`](https://github.com/deadtrickster/prometheus.erl/blob/60bc05871388d9fbed9c76b88e4178d7f0812cb1/src/prometheus_collector.erl#L20-L21) (namely the return type)  
    - There's no quick fix due to `prometheus_vm_memory_collector:collect_mf/2`.  
    - #17 removes the `FIXME`
- [x] [`prometheus_collector:collect_metrics/2`](https://github.com/deadtrickster/prometheus.erl/blob/60bc05871388d9fbed9c76b88e4178d7f0812cb1/src/prometheus_collector.erl#L23-L27)
  - [x] Add real type for `Data`
    - addressed in https://github.com/deadtrickster/prometheus.erl/commit/175eba40fbf7761e8166bd7c361a22ac3d16120d
  - [x] Replace `#'Metric'{}` with `prometheus_model:'Metric'()`
    - Addressed in #16
  - [x] Decide whether `Metrics` should really be one or many https://github.com/deadtrickster/prometheus.erl/commit/4b0de539ca2da872298bab92c940e7945bb15a0f
- [x] Refine `Labels` types in `prometheus_model_helpers`. See `FIXME` tags.

**Comment by deadtrickster** [comment]
maybe introduce separate callback types for `prometheus_collector:callback`? like `mf_callback` and `registry_callback`?

**Comment by yurrriq** [comment]
That sounds good to me. The more specific we can get with the types the better.

**Comment by yurrriq** [comment]
I've added another task from the message on 1cfa8432f33def91cd20c18e369039b4c8c039ef.

**Comment by deadtrickster** [comment]
marked prometheus_metric:value() task as complete: https://github.com/deadtrickster/prometheus.erl/commit/416fd3d131e755809839fa1f163758856567b067

**Comment by deadtrickster** [comment]
aren't this `prometheus_collector:callback() (namely the second clause)` and this `Introduce separate types for prometheus_collector:callback()` task the same?

**Comment by deadtrickster** [comment]
Working on `Refine Labels types in prometheus_model_helpers. See FIXME tags.`

**Comment by deadtrickster** [comment]
marked `Refine Labels types in prometheus_model_helpers. See FXIME tags.` as complete: https://github.com/deadtrickster/prometheus.erl/commit/4bf61e30623e64200b2d616a5df8166d5614b3f8

**Comment by yurrriq** [comment]
> aren't this prometheus_collector:callback() (namely the second clause) and this Introduce separate types for prometheus_collector:callback() task the same?

Yep.

**Comment by deadtrickster** [comment]
marged `Introduce separate types for prometheus_collector:callback()` as complete: https://github.com/deadtrickster/prometheus.erl/commit/bd8be22f49aa710f98b235827509abdbfe971b23

**Comment by deadtrickster** [comment]
`Add real type for Data`
The thing is `Data` can be really anything. For example custom collectors can 'cache' values (like here: https://github.com/deadtrickster/prometheus.erl/blob/master/src/collectors/vm/prometheus_vm_memory_collector.erl#L61). So type is really any().

**Comment by deadtrickster** [comment]
So looks like everything is done. Please let me know what you think.

**Comment by yurrriq** [comment]
LGTM
