### ISSUE TITLE
Blocked publication into hex.pm

### ISSUE THREAD

**Issue by vkatsuba** [deadtrickster/prometheus.erl#122]
Hi All,

Not sure but the changes in the scope of https://github.com/deadtrickster/prometheus.erl/pull/116 looks like will block the publish `prometheus.erl` into [hex.pm](https://hex.pm), please see [docs for publish](https://hex.pm/docs/publish) section **Dependencies**:(C) `Only Hex packages may be used as dependencies of the package ...`(at least there was the same problem in other libs which I'm tried to published :upside_down_face: using the same way).
Issue in adding `git` deps instead of `hex.pm` deps:
```erlang
{deps, [{quantile_estimator, {git, "https://github.com/odo/quantile_estimator"}}]}.
```
instead, eg(just example):
```erlang
{deps, [{quantile_estimator, "0.0.0"}]}.
```
So, up to you :wink:.

Regards,
--V

**Comment by essen** [comment]
Isn't that just when using `mix`?

**Comment by vkatsuba** [comment]
> Isn't that just when using `mix`?

Not sure, I'm not use `Elixir`. But was issue with using [rebar_hex](https://github.com/erlef/rebar3_hex) - as I understand used the same API.

**Comment by deadtrickster** [comment]
I forked it, uploaded to hex, and updated prometheus.erl. Should be enough?

**Comment by vkatsuba** [comment]
> I forked it, uploaded to hex, and updated prometheus.erl. Should be enough?

Yep. Thanks.

**Comment by vkatsuba** [comment]
@deadtrickster one more point, you forgot update `rebar.lock`.

**Comment by deadtrickster** [comment]
haha, right! rebar3 lockfiles are difficult to me. I'm pretty sure I invoked rebar3 lock, but looks like I had to unlock first.

**Comment by vkatsuba** [comment]
Yep. Also not sure if this is important but in fork also missed link to GitHub in https://github.com/deadtrickster/quantile_estimator/blob/master/src/quantile_estimator.app.src, so by this reason in https://hex.pm/packages/quantile_estimator the link to fork on GitHub is not provided. Just need add something like:
```erlang
    ...
    {links, [{"Github", "https://github.com/deadtrickster/quantile_estimator"}]}
    ...
```
to `/src/quantile_estimator.app.src`
