### ISSUE TITLE
Heed the god_modules warning

### ISSUE THREAD

**Issue by yurrriq** [deadtrickster/prometheus.erl#13]
Remove the [hack to allow 38 functions in one module](https://github.com/deadtrickster/prometheus.erl/blob/60bc05871388d9fbed9c76b88e4178d7f0812cb1/elvis.config#L25) and consider splitting up the so-called `god_modules`.

**Comment by deadtrickster** [comment]
TBH I don't think this actually a hack. More like customization too me (well we are overriding public anddocumented setting). I reviewed 'abusive' modules one more time and I just don't see how to decrease functions count without macros/optional args. All this repetitive incs, dincs, observe, dobserve and so on. 
I'm closing this for now but feel free to reopen if you can suggest something.

**Comment by yurrriq** [comment]
:+1:
