### ISSUE TITLE
Bump version

### ISSUE THREAD

**Issue by yurrriq** [deadtrickster/prometheus.erl#15]
Due the recent breaking changes, we ought to bump the version.

**Comment by deadtrickster** [comment]
I reorganized milestones. I really want to 'finish' with typespecs and god modules first. I hope it won't take long (I think two days max). Can you wait?

**Comment by yurrriq** [comment]
Yeah :)

**Comment by deadtrickster** [comment]
https://github.com/deadtrickster/prometheus.erl/releases/tag/v2.0.0
