### ISSUE TITLE
Content-Type negotiation

### ISSUE THREAD

**Issue by deadtrickster** [deadtrickster/prometheus.erl#29]
This is how Accept header looks currently:

`application/vnd.google.protobuf;proto=io.prometheus.client.MetricFamily;encoding=delimited;q=0.7,text/plain;version=0.0.4;q=0.3,application/json;schema=\"prometheus/telemetry\";version=0.0.2;q=0.2,*/*;q=0.1`.

prometheus.erl only supported delimited protobuf and text version 0.0.4

**Comment by deadtrickster** [comment]
Looks like it's too http dependent and should be handler by exporters

**Comment by deadtrickster** [comment]
Looks like there is no standard way to parse accept header yet (will be in next cowlib, what about elli?). I'll write poor's man parser then.

**Comment by aweiker** [comment]
This is how I did it.

```elixir
  def index(conn, _params) do
    accept_headers = get_req_header(conn, "accept")
    format = case Enum.any?(accept_headers, &protobuf?/1) do
      true ->
        Prometheus.Format.Protobuf
      _ ->
        Prometheus.Format.Text
    end

    conn
    |> put_resp_header("Content-Type", format.content_type)
    |> send_resp(200, format.format)
  end

  defp protobuf?(header) do
    String.contains?(header, "protobuf")
  end
end
```

**Comment by deadtrickster** [comment]
While this definitely works it's not entirely correct since nothing mandates only two formats. For example, I'm playing with text/html renderer - really helpful for debugging.

But! At least I know now that someone else cares about content type negotiation too, so thank you a lot!

**Comment by aweiker** [comment]
I just use the text for debugging as I'm lazy and just CTRL+F my way through finding the counter I'm looking for. If you have something that does HTML, then I can see how you would want a real accept header parser.

I'm also very curious what kind of UI you have for the html display. I'm not sure if I would see the value in shipping it inside the current libraries, but it would be interesting.

**Comment by deadtrickster** [comment]
prometheus-plugs now supports content type negotiation using https://github.com/deadtrickster/accept
