### ISSUE TITLE
New time measurement system

### ISSUE THREAD

**Issue by deadtrickster** [deadtrickster/prometheus.erl#32]
Durations measured as difference  between start and end `erlang:monotonic_time`s in so called native time units. native time units are meaningless and have to be converted using `erlang:convert_time_unit`. However as `erlang:convert_time_unit` documentation [warns](http://erlang.org/doc/man/erlang.html#convert_time_unit-3):

```
You may lose accuracy and precision when converting between	time units.
In order to minimize such loss, collect all data at native time unit and do the 
conversion on the end result.
```

The idea is that `set_duration/observe_duration` functions always work with native time units and conversion is delayed until scraping/retrieving value. To implement this, metric needs to know desired time unit. Users can specify desired time unit explicitly via `duration_unit` or mplicitly via metric name ((preferred, since prometheus best practices insists on `<name>_duration_<unit>` metric name format).

Possible units:
 - microseconds;
 - milliseconds;
 - seconds;
 - minutes;
 - hours;
 - days;

Histogram will internally convert buckets bounds to native units if duration_unit is provided. It will convert it back when scraping or retrieving value.

**Comment by talentdeficit** [comment]
this looks excellent. so creating a histogram via `prometheus_histogram:new({thing_duration_milliseconds, ...})` will automatically report that metric as an (integer) millisecond, converted from native units?

**Comment by deadtrickster** [comment]
yep! and if you're not instrumenting directly i.e. Elli gives you 'standard' tuple you can turn this off with duration_unit: false
