### ISSUE TITLE
question about initial gauge/counter values

### ISSUE THREAD

**Issue by massemanet** [deadtrickster/prometheus.erl#37]
I find the sequence below is a bit counter-intuitive.

```
(r@turbot)4> prometheus_gauge:new([{name,"name"},{help,"help me!"}]).
ok
(r@turbot)5> prometheus_gauge:value("name").
undefined
(r@turbot)6> prometheus_gauge:reset("name").
false
(r@turbot)7> prometheus_gauge:value("name").
undefined
(r@turbot)8> prometheus_gauge:set("name",1).
ok
(r@turbot)9> prometheus_gauge:reset("name").
true
(r@turbot)10> prometheus_gauge:value("name").
0
```

 I expected the metric to be created with the default value, and also that reset would always work.

  Is this a bug or a feature?

**Comment by massemanet** [comment]
Thanks for the explanation.

I guess I was confused by this piece of prometheus doc;
"Time series that are not present until something happens are difficult to deal with, as the usual simple operations are no longer sufficient to correctly handle them. To avoid this, export 0 (or NaN, if 0 would be misleading) for any time series you know may exist in advance.
Most Prometheus client libraries (including Go, Java, and Python) will automatically export a 0 for you for metrics with no labels."

https://prometheus.io/docs/practices/instrumentation/

**Comment by deadtrickster** [comment]
Yeah, this library is little bit more explicit here. Again, I think that's because of my use cases and  personally I don't feel like no-labels case should be treated differently. But if it's in the docs I'll leave this issue and hopefully address it shortly after 3.0 release.

**Comment by massemanet** [comment]
thanks.
