### ISSUE TITLE
'protobuf' not found.

### ISSUE THREAD

**Issue by rs7** [deadtrickster/prometheus.erl#39]
Привет, извини, что пишу здесь - не знаю где ещё можно задать вопрос.

При попытке компиляции получаю ошибку

> Unable to run pre hooks for 'compile', command 'compile' in namespace 'protobuf' not found.

rebar3
> {prometheus, {git, "https://github.com/deadtrickster/prometheus.erl.git", {tag, "v3.0.0"}}}

windows 7

**Comment by deadtrickster** [comment]
Привет!

Выглядит как ошибка rebar3, какая у тебя версия? Попробуй обновиться?
У меня нет windows, и, так как ошибка я думаю связана с rebar3, попробуй спросить на Freenode канале #rebar.

**Comment by rs7** [comment]
Я вчера разобрался немного. Мне помогло убрать версию плагина `rebar3_gpb_plugin`, потому-что почему-то он писал что плагин недоступен. И что интересно, только если собирать проект с подключённой библиотекой. Если же, собирать библиотеку отдельно, то этой проблемы не возникает и плагин находится. Магия.

И второе, под виндой хук надо изменить на 
`{post_hooks, [{compile, "sh bin/set-edoc-hidden src/model/prometheus_model.erl"}]}.`

**Comment by deadtrickster** [comment]
Если пришлось убирать версию то тогда, я думаю, точно проблема с rebar3. 

А sh откуда? cygwin или та Убунтонадстройка?

**Comment by rs7** [comment]
Да, скорее всего _rebar3_, или, может, даже _hex.pm_, потому-что в итоге скачалась версия _1.7.2_

Да, _mingw_, благо он входит в поставку _git_-а.

**Comment by deadtrickster** [comment]
Я добавил `sh ` в мастер. Не знаю что делать с rebar3. Ты пробовал поговорить с мейнтенерами?

**Comment by deadtrickster** [comment]
Привет, я закрываю issue. Надеюсь, у тебя всё работает! Если нет, пиши.
