### ISSUE TITLE
Write Documentation

### ISSUE THREAD

**Issue by deadtrickster** [deadtrickster/prometheus.erl#4]
Can hex.pm host edoc generated docs?

Checklist for modules:
- [x] buckets;
- [x] collector;
- [x] format;
- [x] registry;
- [x] vm_memory_collector;
- [x] vm_statistics_collector;
- [x] vm_system_info_collector;
- [x] http;
- [x] protobuf_format;
- [x] text_format;
- [x] counter;
- [x] gauge;
- [x] histogram;
- [x] summary;
- [x] model_helpers.

Checklist for pages:
 - [x] Overview;
 - [x] Time intervals.

**Comment by yurrriq** [comment]
https://hex.pm/docs/tasks#hex_docs

**Comment by yurrriq** [comment]
```erlang
{edoc_opts, [{dir, "docs"}]}.
```
+
```fish
rebar3 edoc
```

will tell [EDoc](http://erlang.org/doc/apps/edoc/chapter.html) to generate its output in `docs/`, which it sounds like https://hexdocs.pm will automatically serve.

**Comment by yurrriq** [comment]
Otherwise, I quite like the GFM output of [edown](https://github.com/uwiger/edown):
```erlang
{profiles, [
  {docs, [{deps, [{edown, "0.8.1}]}]}
]}.

{edoc_opts, [
  {doclet,      edown_doclet},
  {subpackages, true}
]}.
```
