### ISSUE TITLE
rebar2 support

### ISSUE THREAD

**Issue by Stelminator** [deadtrickster/prometheus.erl#69]
Hi, I'm working on a project that's currently using rebar2, and I had some minor trouble adding prometheus.erl in without modification. (I would migrate to rebar3, but it is non-trivial, I want to add metrics/monitoring *first*.)

with just a fresh checkout of prometheus.erl, the following happens:
```
# rebar compile
==> prometheus.erl (compile)
ERROR: Protobuffs library not present in code path!
ERROR: compile failed while processing /<path>/prometheus.erl: rebar_abort
```

This stems from the fact that rebar is trying to generate erlang source from `src/model/prometheus_model.proto`, but the library is not installed.  Since `src/model/prometheus_model.erl` already exists and whatever generate step is not necessary for things to work, my solution was `rm src/model/prometheus_model.proto` and then everything works fine, wrapped in a Makefile.

I tried to ignore or delete the file from rebar, but couldn't find a way to do that when it's used as a dependency.

It would be nice if I didn't have to wrap it with a Makefile.

**Comment by deadtrickster** [comment]
Hi, actually gpb stuff in the separate profile. I don't know why it gets picked-up by rebar2. I may try to figure that out later.

cc @tsloughter

**Comment by tsloughter** [comment]
rebar2 actually comes with 2 protobuf plugins builtin. I think that is what is blowing up.

**Comment by ferd** [comment]
rebar2 has built-in support for protobuffs, but ships (without the actual libraries) and will automatically pick it up; it has no concept of profiles and won't restrict itself to what the config says should happen. If it finds a proto file, it will run gpb on it. 

The workaround for rebar2 as a user would be to grab a protobuffs compiler as a plugin at the top-level or somewhere in your path. There is, as far as I can tell, no way to otherwise tell rebar2 to not compile some sort of file it wants to handle in a dep without forking the dep.

**Comment by deadtrickster** [comment]
Thanks for stepping in guys!

 As Tristan added on IRC, possible solution can be this:
detect rebar2 in config.script as here: http://www.rebar3.org/docs/from-rebar-2x-to-rebar3#section-maintaining-backwards-compatibility-while-using-hex-packages and properly depend on protobuff compiler.

However, rebar2 recognizes only https://github.com/basho/erlang_protobuffs as protobuff compiler - https://github.com/rebar/rebar/blob/2429ddf7b46597222b0eaf6b79a438baafaaa96f/src/rebar_protobuffs_compiler.erl#L85 which is deprectated too (and not used here).

**Comment by deadtrickster** [comment]
Actually gpb can be set - https://github.com/rebar/rebar/blob/master/rebar.config.sample#L92-L105.  :-)

**Comment by Stelminator** [comment]
@deadtrickster ah, cool.
So far here's what I've got, in case anyone else comes across this before I can make a pull request with something parameterized for rebar versions and whether or not to do the protobuff compiling.

### Option 1: Just don't do the protobuff compile.
```diff
--- a/rebar.config
+++ b/rebar.config
@@ -16,6 +16,8 @@
 {coveralls_coverdata    , "_build/test/cover/eunit.coverdata"}.
 {coveralls_service_name , "travis-ci"}.

+{proto_opts, [{src_dirs, []}]}.
+
 {xref_extra_paths,[]}.
 {xref_checks,[undefined_function_calls,undefined_functions,locals_not_used,
               deprecated_function_calls,deprecated_functions]}.
```

### Option 2: Do the protobuff compile, but require gpb dependency.
```diff
--- a/rebar.config
+++ b/rebar.config
@@ -1,10 +1,10 @@
 %% -*- mode: erlang -*-
-{erl_opts, [debug_info]}.
+{erl_opts, [debug_info, {i, "deps/gpb/include"}]}.

 %% Awesomely bad hack to ensure prometheus_model is hidden from docs.
 {post_hooks, [{"(linux|darwin|solaris|freebsd|netbsd|openbsd)",
                compile, "sh bin/set-edoc-hidden src/model/prometheus_model.erl"}]}.
-{deps, []}.
+{deps, [{gpb, ".*", {git, "git@github.com:tomas-abrahamsson/gpb.git", {branch, "master"}}}]}.
 {shell, [{apps, [prometheus]}]}.
 {cover_enabled, true}.
 {cover_export_enabled, true}.
@@ -16,6 +16,12 @@
 {coveralls_coverdata    , "_build/test/cover/eunit.coverdata"}.
 {coveralls_service_name , "travis-ci"}.

+{proto_opts, [
+              {compiler, gpb},
+              {src_dirs, ["src/model"]}
+             ]}.
+{gpb_opts,  [{o_erl, "src/model"}]}.
+
 {xref_extra_paths,[]}.
 {xref_checks,[undefined_function_calls,undefined_functions,locals_not_used,
               deprecated_function_calls,deprecated_functions]}.
```

**Comment by deadtrickster** [comment]
Awesome! I think Option 1(overriding proto_opts) should go to the script. 
Normal process is to regenerate model by hand anyway.

**Comment by Stelminator** [comment]
That's sounds fine to me.  Great!  Also, it fixes my issue.  Thanks!
