### ISSUE TITLE
is it possible to add a prefix to metrics?

### ISSUE THREAD

**Issue by manuel-rubio** [deadtrickster/prometheus.erl#73]
I'm checking the metrics are retrieved in this way:

```
erlang_vm_memory_bytes_total{kind="system"} 46309272
erlang_vm_memory_bytes_total{kind="processes"} 102828968
```

I've different servers and I want to add a prefix to that metric, is it possible? are there a better option to do that? Thanks.

**Comment by deadtrickster** [comment]
You don't need to do this! Prometheus automatically attaches instance and job labels to each metric. Plus, you can add more labels in your scrape config. https://prometheus.io/docs/concepts/jobs_instances/

**Comment by manuel-rubio** [comment]
Ok, thanks!
