### ISSUE TITLE
Add node label to all metrics

### ISSUE THREAD

**Issue by gerhard** [deadtrickster/prometheus.erl#88]
I believe that all metrics coming from an Erlang node should be labelled with `node/0`, i.e.:

```
...
# TYPE rabbitmq_node_io_read_bytes gauge
# HELP rabbitmq_node_io_read_bytes Bytes read since node start.
rabbitmq_node_io_read_bytes{node="rabbit@focker"} 1
# TYPE rabbitmq_node_io_read_microseconds gauge
# HELP rabbitmq_node_io_read_microseconds Total time of read operations.
rabbitmq_node_io_read_microseconds{node="rabbit@focker"} 10
...
```

Yes, this could be achieved in Prometheus, but spreading a node's identity into multiple places presents operational challenges that don't scale well. Ideally, every metric coming from an Erlang node will already be labelled with the Erlang node name.

It's OK to make this non-default & completely optional. If you are not completely against this idea, happy to attempt a PR. I have made a first attempt in https://github.com/rabbitmq/rabbitmq-prometheus/commit/78703c710fe54199653cb24cd8107d13158b21ed

**Comment by gerhard** [comment]
Could constant labels introduced in https://github.com/deadtrickster/prometheus.erl/commit/22a774471a340ce161c317dc0bd5288bc709c0f6 be what I'm after? Taking a closer look...

**Comment by gerhard** [comment]
https://github.com/rabbitmq/rabbitmq-prometheus/commit/e352b00f0037396243fd25d5eed8be73c277bdc4 did the trick for `prometheus_rabbitmq_core_metrics_collector`.

It would be nice to define a **global** label that would be applied to all metrics, including those coming from `?DEFAULT_COLLECTORS`.

**Comment by deadtrickster** [comment]
Hi, looks like it's a bit inconsistent now. Constant labels applied to counters, gauges, etc, but not to metrics coming from collectors. 

Perhaps a good place to add global constant labels would be https://github.com/deadtrickster/prometheus.erl/blob/master/src/prometheus_collector.erl#L141. Wrapping callback and injecting. Global constant labels likely come from config.

However, https://github.com/rabbitmq/rabbitmq-prometheus/commit/e352b00f0037396243fd25d5eed8be73c277bdc4 calls a function... Will it be fine for you to put node name in sys.config? I also don't mind some kind of preprocessing (e.g. expanding '\_\_node\_\_' to the result of node() call).

**Comment by essen** [comment]
Maybe instead of using `prometheus_vm_memory_collector` directly we can have `rabbitmq_prometheus_vm_memory_collector` that wraps the functions in `prometheus_vm_memory_collector` and adds the labels we want? The module should be trivial to write and would not require any prometheus.erl changes.

Alternatively maybe `prometheus_vm_memory_collector` should just add a node label? How do you currently use it in a cluster? Is it possible that our `node` label is not actually needed at all and there's an equivalent way of doing things that doesn't require it?

**Comment by deadtrickster** [comment]
@essen, AFAIK things like node usually added via scraping config, maybe even relabeling. I'm all for configurable static labels though

**Comment by gerhard** [comment]
I like the idea of having a single way of adding labels to all metrics, regardless which collectors they are coming from. Btw, these labels may change after node boot. One such label would be `cluster_name` - https://github.com/rabbitmq/rabbitmq-server/blob/v3.8.0-beta.3/src/rabbit_nodes.erl#L74-L76, which is RabbitMQ-specific.

Scraping config is one way of adding these type of "static" labels. In Prometheus there are different flavours of service discovery, including JSON file, as well as static config. Who wants to support different integration strategies? What about RabbitMQ installed from package? And docker-compose? I see a lot of operational complexity if we go down this path.

The alternative that I'm proposing is to use node-native identities, like node name & cluster_name (less relevant outside of RabbitMQ). These labels would be opt-in, nothing would change for current users.

**Comment by deadtrickster** [comment]
@gerhard, what you think about this? https://github.com/deadtrickster/prometheus.erl/issues/88#issuecomment-481975187

**Comment by gerhard** [comment]
> Perhaps a good place to add global constant labels would be https://github.com/deadtrickster/prometheus.erl/blob/master/src/prometheus_collector.erl#L141. Wrapping callback and injecting. Global constant labels likely come from config.

Even though I can't imagine how this would work, this does feel like a good integration point.

> However, [rabbitmq/rabbitmq-prometheus@e352b00](https://github.com/rabbitmq/rabbitmq-prometheus/commit/e352b00f0037396243fd25d5eed8be73c277bdc4) calls a function... Will it be fine for you to put node name in sys.config? I also don't mind some kind of preprocessing (e.g. expanding '__node__' to the result of node() call).

While labels are global and constant, their values would need to be computed: e.g. `node()` vs `rabbit@rabbitmq1`

How about registering global labels like this?

```
prometheus_registry:add_global_label({node, node()})
prometheus_registry:add_global_label({cluster, rabbitmq_nodes:cluster_name()})
```

Not sure how you were thinking of wrapping the `Callback` in `Collector:collect_mf(Registry, Callback)`

**Comment by essen** [comment]
I think the same can be achieved via `sys.config`, because we can set configuration values at startup and could therefore compute the necessary values at run time. So in RabbitMQ we would load prometheus.erl and then call `application:set_env` to define the global labels we want. Which means that prometheus.erl can look into this configuration at https://github.com/deadtrickster/prometheus.erl/blob/master/src/prometheus_collector.erl#L141 and add the labels directly from both static (`sys.config`) and dynamic (`application:set_env`) configuration with no other changes necessary.

I can probably try doing this next week.

**Comment by deadtrickster** [comment]
> both static (sys.config) and dynamic (application:set_env) 

but sys.config loaded to env, right? so indistinguishable. Just need to merge. Or what :-)?

**Comment by essen** [comment]
Yes it's indistinguishable, that's what I was trying to say. We would be fine with prometheus.erl just reading from application env so I think we should do it.

**Comment by deadtrickster** [comment]
Hi, can this be closed?

**Comment by gerhard** [comment]
👍
